const SUBSCRIBTION_KEYS = {
    OPEN_ACTIONS_ACTIONSHEET: 'OPEN_ACTIONS_ACTIONSHEET',
    OPEN_CREATE_TRANSFER_TEMPLATE: 'OPEN_CREATE_TRANSFER_TEMPLATE',
    OPEN_CREATE_PAYMENT_TEMPLATE: 'OPEN_CREATE_PAYMENT_TEMPLATE',
    SET_ACTIVE_ROUTE: 'SET_ACTIVE_ROUTE',
    FETCH_USER_ACCOUNTS: 'FETCH_USER_ACCOUNTS',
    OPEN_CARDS_STOTE: 'OPEN_CARDS_STOTE',
    START_TOPUP: 'START_TOPUP',
    ADD_BANK_CARD: 'ADD_BANK_CARD',
    PWDCODE_UPDATED: 'PWDCODE_UPDATED',
    UPDATE_TOKEN: 'UPDATE_TOKEN'
}

export default SUBSCRIBTION_KEYS;